USE [master]
GO
/****** Object:  Database [WineShop_ManavDataBase]    Script Date: 05-Apr-2021 14:16:15 ******/
CREATE DATABASE [WineShop_ManavDataBase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WineShop_ManavDataBase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WineShop_ManavDataBase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WineShop_ManavDataBase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WineShop_ManavDataBase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [WineShop_ManavDataBase] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WineShop_ManavDataBase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [WineShop_ManavDataBase] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET ARITHABORT OFF 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET  ENABLE_BROKER 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET RECOVERY FULL 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET  MULTI_USER 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [WineShop_ManavDataBase] SET DB_CHAINING OFF 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [WineShop_ManavDataBase] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'WineShop_ManavDataBase', N'ON'
GO
ALTER DATABASE [WineShop_ManavDataBase] SET QUERY_STORE = OFF
GO
USE [WineShop_ManavDataBase]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 05-Apr-2021 14:16:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customers]    Script Date: 05-Apr-2021 14:16:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customers](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Age] [int] NOT NULL,
	[Email] [nvarchar](max) NULL,
	[Gender] [nvarchar](max) NULL,
	[Name] [nvarchar](max) NULL,
	[RateListID] [int] NOT NULL,
	[WineID] [int] NOT NULL,
 CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RateLists]    Script Date: 05-Apr-2021 14:16:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RateLists](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Price] [nvarchar](max) NULL,
 CONSTRAINT [PK_RateLists] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Wines]    Script Date: 05-Apr-2021 14:16:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Wines](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NULL,
 CONSTRAINT [PK_Wines] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20210405110351_Init1', N'2.0.3-rtm-10026')
GO
SET IDENTITY_INSERT [dbo].[Customers] ON 
GO
INSERT [dbo].[Customers] ([ID], [Age], [Email], [Gender], [Name], [RateListID], [WineID]) VALUES (1, 20, N'Manav@gmail.com', N'Male', N'Manav Preet', 1, 1)
GO
SET IDENTITY_INSERT [dbo].[Customers] OFF
GO
SET IDENTITY_INSERT [dbo].[RateLists] ON 
GO
INSERT [dbo].[RateLists] ([ID], [Price]) VALUES (1, N'500')
GO
SET IDENTITY_INSERT [dbo].[RateLists] OFF
GO
SET IDENTITY_INSERT [dbo].[Wines] ON 
GO
INSERT [dbo].[Wines] ([ID], [Name]) VALUES (1, N'Signature')
GO
SET IDENTITY_INSERT [dbo].[Wines] OFF
GO
/****** Object:  Index [IX_Customers_RateListID]    Script Date: 05-Apr-2021 14:16:15 ******/
CREATE NONCLUSTERED INDEX [IX_Customers_RateListID] ON [dbo].[Customers]
(
	[RateListID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Customers_WineID]    Script Date: 05-Apr-2021 14:16:15 ******/
CREATE NONCLUSTERED INDEX [IX_Customers_WineID] ON [dbo].[Customers]
(
	[WineID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Customers]  WITH CHECK ADD  CONSTRAINT [FK_Customers_RateLists_RateListID] FOREIGN KEY([RateListID])
REFERENCES [dbo].[RateLists] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Customers] CHECK CONSTRAINT [FK_Customers_RateLists_RateListID]
GO
ALTER TABLE [dbo].[Customers]  WITH CHECK ADD  CONSTRAINT [FK_Customers_Wines_WineID] FOREIGN KEY([WineID])
REFERENCES [dbo].[Wines] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Customers] CHECK CONSTRAINT [FK_Customers_Wines_WineID]
GO
USE [master]
GO
ALTER DATABASE [WineShop_ManavDataBase] SET  READ_WRITE 
GO
