// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WineShop_Manav.Data;

namespace WineShop_Manav.Migrations.WineShopDb
{
    [DbContext(typeof(WineShopDbContext))]
    partial class WineShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WineShop_Manav.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Email");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<int>("RateListID");

                    b.Property<int>("WineID");

                    b.HasKey("ID");

                    b.HasIndex("RateListID");

                    b.HasIndex("WineID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("WineShop_Manav.Models.RateList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Price");

                    b.HasKey("ID");

                    b.ToTable("RateLists");
                });

            modelBuilder.Entity("WineShop_Manav.Models.Wine", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Wines");
                });

            modelBuilder.Entity("WineShop_Manav.Models.Customer", b =>
                {
                    b.HasOne("WineShop_Manav.Models.RateList", "RateList")
                        .WithMany("Customers")
                        .HasForeignKey("RateListID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WineShop_Manav.Models.Wine", "Wine")
                        .WithMany("Customers")
                        .HasForeignKey("WineID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
